apiVersion: v1
kind: Service
metadata:
  name: fesvc
  labels:
    app: fesvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8888
  selector:
    app: fesvc
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fesvc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fesvc
    spec:
      containers:
      - name: fesvc
        image: iljoong/fesvc:latest
        ports:
          - name: web
            containerPort: 8888
          - name: debug
            containerPort: 8889          
        command: ["/app/init_container.sh", "-timeout", "200", "-mode", "seq"]
        env:
        - name: GO_WEBBACKENDS
          value: besvcweb:36060
        - name: GO_IMGBACKENDS
          value: besvcimg:36060
        - name: GO_VIDBACKENDS
          value: besvcvid:36060
      imagePullSecrets:
      - name: ""